services:
  rabbitmq:
    image: "rabbitmq:4.2.2-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - amq-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  

networks:
  amq-network:
    driver: bridge

volumes:
  rabbitmq-data:
